### ISSUE TITLE
关于服务器通讯的问题

### ISSUE THREAD

**Issue by hyangl** [freeeyes/PSS#13]
1. ClientProConnectManager.cpp中 CClientProConnectManager::Close(int nServerID, EM_s2s ems2s)，m_objClientTCPList删除的时候是否要加锁

2. ClientProConnectManager.cpp中CClientProConnectManager::Connect 中异步才需要 AddClientMessage，而且没有地方DelClientMessage

3. ClientInfo，Client和ClientMessage调用问题：
   -  CClientProConnectManager::Close时刚好执行handle_timeout，则可能ClientInfo已经free，但是handle_timeout中仍会调用；
   - Client read过程中，外部调用close，则ClienetMessage可能free，导致Client中调用ClientMessage异常

**Comment by freeeyes** [comment]
已更新相关代码。
请测试并反馈结果。
