### ISSUE TITLE
时间轮盘问题

### ISSUE THREAD

**Issue by cuijw** [freeeyes/PSS#17]
# 问题描述(question) 
过期的连接通过tick来清理，没有重置blockID为INVAILD_BLOCKID。当m_pBlockIDList所有位置都占用后，索表m_htIndexList无法成功添加BlockID,但是对应BlockID的容器已经 添加成功了连接对象，就会出现一个现象就是过一个时间轮盘周期，就会断开一次连接。客户端连接上来的连接会经常周期性断开。
## 操作系统环境(OS Environment):   
centos 7.0
## ACE版本环境(ACE Version):  
ACE版本是6.4
## PSS配置文件信息(PSS configure XML file content):  
<ClientInfo HandlerCount="5000" MaxHandlerCount="10000" MaxConnectTime="120" CheckAliveTime="60" MaxBuffRecv="1024"  desc="客户端链接相关参数"/>

**Comment by freeeyes** [comment]
已解决。
