### ISSUE TITLE
建议把邮件告警部分剥离开，在插件中实现。

### ISSUE THREAD

**Issue by 170fangjun** [freeeyes/PSS#20]
# 问题描述(question) 

PSS引入了libcurl，导致编译需要curl才行。建议把邮件告警部分剥离开，在插件中实现，这样pss编译还是只需要ace即可，不加邮件告警插件就不发邮件告警，如果有邮件告警插件，可以在插件中实现邮件告警。

**Comment by freeeyes** [comment]
我已经修复这个问题了，解决方式是，在生成编译文件的时候自动寻找libcurl，如果有，则https 邮件代码会自动编译，否则，不会编译curl相关功能，做到了无感知。
