### ISSUE TITLE
建议能增加cpu绑定功能

### ISSUE THREAD

**Issue by liuchao412** [freeeyes/PSS#27]
问题描述(question)
建议能增加cpu绑定功能

操作系统环境(OS Environment):
ACE版本环境(ACE Version):
PSS配置文件信息(PSS configure XML file content): 默认
逻辑过程描述(Logic plugin describe): 默认
问题描述(Question describe):默认
堆栈信息(Stack information): 默认
期待结果(Expected results): 默认

**Comment by freeeyes** [comment]
it's finished
