### ISSUE TITLE
Win10 VS2017 Debug模式 Win32、x64编译插件Login失败

### ISSUE THREAD

**Issue by jiagithub** [freeeyes/PSS#28]
Loin的默认工程配置不正确，Debug模式下，无论Win32还是x64都会提示找不到文件的情况，另外编译过程中提示basecommand.cpp(175): error C2664: “bool IClientManager::SendData(int,char *&,int,bool)”: 无法将参数 2 从“char [200]”转换为“char *&”

**Comment by jiagithub** [comment]
CommonTCPClient的工程文件无法通过VS2017打开成功

**Comment by freeeyes** [comment]
哪个文件夹，哪个文件，该送我一下。

**Comment by jiagithub** [comment]
example-Module/LoginBuffer/Login下的解决方案文件在vs2017下编译不通过。另外就是编译该目录下的BaseCommand.cpp 175行提示错误

**Comment by freeeyes** [comment]
我提交了，你看下。
