### ISSUE TITLE
框架加载插件流程更新须考虑兼容旧的插件加载方式

### ISSUE THREAD

**Issue by sidanagan** [freeeyes/PSS#30]
我方在把代码迁移到新框架上来时，出现了无法连接第三方服务的现象。原因是因为在ClientReConnectManager.cpp文件中CClientReConnectManager::ConnectTcpInit这个函数先于CClientReConnectManager::Init函数被调用了

在连接远程的时候，不能在LoadModule()进行，要在InitModule()进行。
这个我下周抽时间改一下，兼容你的老模式，在LoadModule()进行，要在InitModule() 都可以进行。

**Comment by freeeyes** [comment]
这里已经支持了。
