### ISSUE TITLE
客户端连不上服务器

### ISSUE THREAD

**Issue by xujie10101** [freeeyes/PSS#34]
linux下的LGLogic模块，客户端连接不上服务器，windows下正常

**Comment by freeeyes** [comment]
你在群里吗？

**Comment by xujie10101** [comment]
在的
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"freeeyes"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年12月25日(星期三) 中午11:33
 收件人:&nbsp;"freeeyes/PSS"<PSS@noreply.github.com&gt;;
 抄送:&nbsp;"782575063"<782575063@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [freeeyes/PSS] 客户端连不上服务器 (#34)

 

 
你在群里吗？

**Comment by freeeyes** [comment]
请参考 forward.xml的配置。
