### ISSUE TITLE
关于linux下crash的问题

### ISSUE THREAD

**Issue by zhs007** [freeeyes/PSS#8]
我们的服务器程序在linux下，crash非常频繁，请问有比较好的调试方案么？我们想做一些逻辑测试，请问有比较合适的方案或模拟客户端框架么？

**Comment by freeeyes** [comment]
看你们是那种服务，可以用PassTCP压测指定命令。在服务器抓core即可分析。

**Comment by zhs007** [comment]
crash怎么处理呢？底层做过一些处理么，譬如中断回调这些呢？有对调用堆栈输出的进一步支持么？

**Comment by freeeyes** [comment]
你可以加PSS的群，至于调试是基本功问题。会用gdb就会调试core文件。
