### ISSUE TITLE
关于一个服务器上运行多个PSS服务

### ISSUE THREAD

**Issue by 170fangjun** [freeeyes/PSS#9]
现在我的方法是启动的时候导入一个环境变量。
export LD_LIBRARY_PATH=./;
这样进程会寻找当前目录下的解析so
是否还有其他的方法呢。。

**Comment by 170fangjun** [comment]
如果在编译上修改的话，难免PSS主程序会和SVN上不一致，而且需要维护2套代码。

**Comment by freeeyes** [comment]
首先，编译文件，你完全可以独立出来，用你自己的编辑文件。
Linux下：
在Linux_Bin目录下打开makefile.mpc。
找到 libs += PacketParse 把这个插件名称换成你自己的插件名称即可。
然后重新运行runlinuxmpc.sh 即可。
Windows下：
修改 属性 -> 连接器 ->附加依赖项中的，PacketParse.lib为你自己插件的名字即可。

NOTE:PackeyParse工程你可以任意改成你要的工程名称，这样就能保证一台机器上运行不同的PSS实例。
